name: "Print out changelog"
description: "Print out changelog for the two git references"
inputs:
  from:
    description: "The git reference to start from"
    required: false
  to:
    description: "The git reference to end at"
    required: false
outputs:
  changelog:
    value: ${{ steps.print.outputs.changelog }}
    description: "The changelog"

runs:
  using: "composite"
  steps:
    - name: ðŸ–¥ï¸ Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: ðŸ”¬ Check semantic versioning
      id: print
      shell: bash
      run: |
        GITHUB_REF=${{ github.head_ref || github.ref_name }} 
        npx semantic-release --no-ci --dry-run --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator --branches $GITHUB_REF | sed -n '/^##/,$p' > output.txt
        OUTPUT=$(cat output.txt)
        echo "changelog<<EOF"$'\n'"$OUTPUT"$'\n'EOF >> "$GITHUB_OUTPUT"
